cc_library(
    name = "pj",
    srcs = ["pj.cc"],
    hdrs = ["pj.cc"],
    deps = [":util"]
)

cc_library(
    name = "pmj",
    srcs = ["pmj.cc"],
    hdrs = ["pmj.cc"],
    deps = [":util"]
)

cc_library(
    name = "pmj02",
    srcs = ["pmj02.cc"],
    hdrs = ["pmj02.cc"],
    deps = [":util"]
)

cc_library(
    name = "util",
    srcs = ["util.cc"],
    hdrs = ["util.cc"],
)